//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace LongTermCare_Xml_.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="notechSoap", Namespace="http://tempuri.org/")]
    public partial class notech : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncryptTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_tree_noOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_portal_typeOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_portal_accountOperationCompleted;
        
        private System.Threading.SendOrPostCallback importOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public notech() {
            this.Url = global::LongTermCare_Xml_.Properties.Settings.Default.LongTermCare_Xml__WebReference_notech;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event EncryptTextCompletedEventHandler EncryptTextCompleted;
        
        /// <remarks/>
        public event search_tree_noCompletedEventHandler search_tree_noCompleted;
        
        /// <remarks/>
        public event search_portal_typeCompletedEventHandler search_portal_typeCompleted;
        
        /// <remarks/>
        public event search_portal_accountCompletedEventHandler search_portal_accountCompleted;
        
        /// <remarks/>
        public event importCompletedEventHandler importCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EncryptText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncryptText(string password) {
            object[] results = this.Invoke("EncryptText", new object[] {
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptTextAsync(string password) {
            this.EncryptTextAsync(password, null);
        }
        
        /// <remarks/>
        public void EncryptTextAsync(string password, object userState) {
            if ((this.EncryptTextOperationCompleted == null)) {
                this.EncryptTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptTextOperationCompleted);
            }
            this.InvokeAsync("EncryptText", new object[] {
                        password}, this.EncryptTextOperationCompleted, userState);
        }
        
        private void OnEncryptTextOperationCompleted(object arg) {
            if ((this.EncryptTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptTextCompleted(this, new EncryptTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/search_tree_no", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int search_tree_no(string uuid, int type) {
            object[] results = this.Invoke("search_tree_no", new object[] {
                        uuid,
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void search_tree_noAsync(string uuid, int type) {
            this.search_tree_noAsync(uuid, type, null);
        }
        
        /// <remarks/>
        public void search_tree_noAsync(string uuid, int type, object userState) {
            if ((this.search_tree_noOperationCompleted == null)) {
                this.search_tree_noOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_tree_noOperationCompleted);
            }
            this.InvokeAsync("search_tree_no", new object[] {
                        uuid,
                        type}, this.search_tree_noOperationCompleted, userState);
        }
        
        private void Onsearch_tree_noOperationCompleted(object arg) {
            if ((this.search_tree_noCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_tree_noCompleted(this, new search_tree_noCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/search_portal_type", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int search_portal_type(string type) {
            object[] results = this.Invoke("search_portal_type", new object[] {
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void search_portal_typeAsync(string type) {
            this.search_portal_typeAsync(type, null);
        }
        
        /// <remarks/>
        public void search_portal_typeAsync(string type, object userState) {
            if ((this.search_portal_typeOperationCompleted == null)) {
                this.search_portal_typeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_portal_typeOperationCompleted);
            }
            this.InvokeAsync("search_portal_type", new object[] {
                        type}, this.search_portal_typeOperationCompleted, userState);
        }
        
        private void Onsearch_portal_typeOperationCompleted(object arg) {
            if ((this.search_portal_typeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_portal_typeCompleted(this, new search_portal_typeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/search_portal_account", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool search_portal_account(string user_id, string password) {
            object[] results = this.Invoke("search_portal_account", new object[] {
                        user_id,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void search_portal_accountAsync(string user_id, string password) {
            this.search_portal_accountAsync(user_id, password, null);
        }
        
        /// <remarks/>
        public void search_portal_accountAsync(string user_id, string password, object userState) {
            if ((this.search_portal_accountOperationCompleted == null)) {
                this.search_portal_accountOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_portal_accountOperationCompleted);
            }
            this.InvokeAsync("search_portal_account", new object[] {
                        user_id,
                        password}, this.search_portal_accountOperationCompleted, userState);
        }
        
        private void Onsearch_portal_accountOperationCompleted(object arg) {
            if ((this.search_portal_accountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_portal_accountCompleted(this, new search_portal_accountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/import", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string import(int USERS_TREE_NO, int users_type_no, string name, string user_id, string password, string e_mail, string id, int sex_no, int is_leaf) {
            object[] results = this.Invoke("import", new object[] {
                        USERS_TREE_NO,
                        users_type_no,
                        name,
                        user_id,
                        password,
                        e_mail,
                        id,
                        sex_no,
                        is_leaf});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void importAsync(int USERS_TREE_NO, int users_type_no, string name, string user_id, string password, string e_mail, string id, int sex_no, int is_leaf) {
            this.importAsync(USERS_TREE_NO, users_type_no, name, user_id, password, e_mail, id, sex_no, is_leaf, null);
        }
        
        /// <remarks/>
        public void importAsync(int USERS_TREE_NO, int users_type_no, string name, string user_id, string password, string e_mail, string id, int sex_no, int is_leaf, object userState) {
            if ((this.importOperationCompleted == null)) {
                this.importOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportOperationCompleted);
            }
            this.InvokeAsync("import", new object[] {
                        USERS_TREE_NO,
                        users_type_no,
                        name,
                        user_id,
                        password,
                        e_mail,
                        id,
                        sex_no,
                        is_leaf}, this.importOperationCompleted, userState);
        }
        
        private void OnimportOperationCompleted(object arg) {
            if ((this.importCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importCompleted(this, new importCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EncryptTextCompletedEventHandler(object sender, EncryptTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void search_tree_noCompletedEventHandler(object sender, search_tree_noCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_tree_noCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_tree_noCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void search_portal_typeCompletedEventHandler(object sender, search_portal_typeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_portal_typeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_portal_typeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void search_portal_accountCompletedEventHandler(object sender, search_portal_accountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_portal_accountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_portal_accountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void importCompletedEventHandler(object sender, importCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal importCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591