//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongTermCare_Xml_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOPInstance
    {
        public string SOPClassUID { get; set; }
        public string SOPInstanceUID { get; set; }
        public string SeriesInstanceUID { get; set; }
        public string InstanceCreationDate { get; set; }
        public string InstanceCreationTime { get; set; }
        public string InstanceCreatorUID { get; set; }
        public string DeviceType { get; set; }
        public string DeviceRecordResult { get; set; }
        public string ContributingEquipmentSequence { get; set; }
    }
}
