//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongTermCare_Xml_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public string StudyDate { get; set; }
        public string StudyTime { get; set; }
        public string StudyDescription { get; set; }
        public string PatientID { get; set; }
        public string StudyInstanceUID { get; set; }
        public string StudyID { get; set; }
        public string AccessionNumber { get; set; }
        public string ReferringPhysiciansName { get; set; }
    }
}
